<Project>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
  </PropertyGroup>

  <PropertyGroup>
    <Version>0.2.0</Version>
    <Authors>Andrey Golyakov</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/golyakoff/ago-platform</RepositoryUrl>
    <PackageProjectUrl>https://github.com/golyakoff/ago-platform</PackageProjectUrl>
  </PropertyGroup>

</Project>
