<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Mono.Cecil" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Ago.Platform.Kernel\Ago.Platform.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Hosting\Ago.Platform.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Abstractions\Ago.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Persistence.Postgres\Ago.Platform.Persistence.Postgres.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Messaging.RabbitMq\Ago.Platform.Messaging.RabbitMq.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Observability\Ago.Platform.Observability.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Realtime\Ago.Platform.Realtime.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Resilience\Ago.Platform.Resilience.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Caching.Redis\Ago.Platform.Caching.Redis.csproj" />
    <ProjectReference Include="..\..\src\Ago.Platform.Storage.S3\Ago.Platform.Storage.S3.csproj" />
  </ItemGroup>

</Project>
