<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="StackExchange.Redis" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ago.Platform.Abstractions\Ago.Platform.Abstractions.csproj" />
    <ProjectReference Include="..\Ago.Platform.Kernel\Ago.Platform.Kernel.csproj" />
    <ProjectReference Include="..\Ago.Platform.Resilience\Ago.Platform.Resilience.csproj" />
  </ItemGroup>

</Project>
